/* Assistant hors ligne : réponses rédigées à l'avance, avec sources. Ne répond JAMAIS sans source locale.
   Un vrai assistant IA nécessite un serveur (voir README). */
const KB = [
  { k: ["hegire", "hijra", "emigration", "emigrer", "migration"], title: "Pourquoi l'Hégire a-t-elle eu lieu ?",
    a: "À La Mecque, les premiers musulmans subissaient des persécutions. Des habitants de Yathrib (future Médine) se sont engagés à protéger le Prophète ﷺ lors des pactes d'Aqaba. Le Prophète ﷺ a donc émigré à Médine en 622, accompagné d'Abu Bakr, et la première communauté musulmane organisée s'y est établie.",
    src: [["Texte", "Coran 9:40 (le Prophète et son compagnon dans la grotte)"], ["Texte", "Coran 8:30 (le complot des Qurayshites)"], ["Histoire", "Sîra d'Ibn Hichâm"]],
    nuance: "Le lien entre certains versets et l'Hégire relève de l'interprétation des exégètes. Les détails chronologiques varient selon les récits." },
  { k: ["combien", "priere", "prieres", "salat", "rakat"], title: "Combien de prières par jour ?",
    a: "Cinq prières sont obligatoires chaque jour : Fajr (2 rak'at), Dhuhr (4), Asr (4), Maghrib (3), Isha (4).",
    src: [["Texte", "Coran 4:103 (prière prescrite à des heures déterminées)"], ["Texte", "Coran 20:14"], ["Hadith", "Hadith des cinq piliers (Bukhari 8, Muslim 16)"]] },
  { k: ["zakat", "aumone", "pourcentage", "nissab"], title: "Quel est le taux de la zakat ?",
    a: "Le taux usuel sur l'épargne monétaire est de 2,5 % pour la richesse qui dépasse le nissab et a été détenue un an lunaire. Le Coran cite huit catégories de bénéficiaires.",
    src: [["Texte", "Coran 9:60"], ["Hadith", "Hadith des cinq piliers (Bukhari 8, Muslim 16)"]],
    nuance: "La valeur du nissab et certains détails de calcul varient selon les écoles juridiques et les époques : demande à une personne qualifiée." },
  { k: ["ramadan", "jeune", "jeuner", "siyam"], title: "Pourquoi jeûne-t-on en Ramadan ?",
    a: "Le jeûne du Ramadan est prescrit par Allah aux croyants « afin que vous atteigniez la piété ». On s'abstient de manger, de boire et des relations conjugales de l'aube au coucher du soleil.",
    src: [["Texte", "Coran 2:183-185"]] },
  { k: ["coran", "sourate", "revelation", "revele"], title: "Qu'est-ce que le Coran ?",
    a: "Les musulmans croient que le Coran est la parole d'Allah révélée au Prophète ﷺ par l'ange Jibril sur environ 23 ans. Il compte 114 sourates.",
    src: [["Texte", "Coran 2:185"], ["Texte", "Coran 15:9 (préservation)"]] },
  { k: ["tawhid", "unicite", "shirk", "associer"], title: "Qu'est-ce que le tawhid ?",
    a: "Le tawhid est la croyance en l'unicité d'Allah. Son contraire est le shirk : associer quelqu'un à Allah.",
    src: [["Texte", "Coran 112"], ["Texte", "Coran 4:48"]] },
  { k: ["piliers", "pilier", "cinq"], title: "Quels sont les piliers de l'Islam ?",
    a: "Il y en a cinq : la chahada, la salat, la zakat, le jeûne de Ramadan et le pèlerinage à La Mecque pour qui en a la capacité.",
    src: [["Hadith", "Bukhari 8 ; Muslim 16"]] },
  { k: ["hira", "iqra", "premiere", "revelation", "jibril"], title: "Comment a eu lieu la première révélation ?",
    a: "Dans la grotte de Hira, l'ange Jibril est apparu au Prophète ﷺ et lui a dit « Iqra » (lis / récite). Les premiers versets sont ceux de la sourate Al-'Alaq. Khadija l'a rassuré puis l'a emmené chez Waraqa ibn Nawfal.",
    src: [["Texte", "Coran 96:1-5"], ["Hadith", "Bukhari 3"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["ablution", "ablutions", "woudou", "wudu", "purification"], title: "Comment fait-on les ablutions ?",
    a: "Intention et « Bismillah », mains, bouche, nez, visage, bras jusqu'aux coudes, essuyage de la tête et des oreilles, pieds jusqu'aux chevilles.",
    src: [["Texte", "Coran 5:6"]], nuance: "Les détails (ordre, nombre de lavages, ce qui annule les ablutions) varient légèrement selon les écoles." },
  { k: ["amin", "jeunesse", "khadija", "mariage"], title: "Qui était al-Amin ?",
    a: "Al-Amin (« le digne de confiance ») est le surnom donné à Muhammad ﷺ dans sa jeunesse à La Mecque. Il a épousé Khadija vers l'âge de 25 ans.",
    src: [["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["allah", "dieu"], title: "Qui est Allah ?",
    a: "Allah est le nom de Dieu en arabe : l'Unique, le Créateur, sans associé, qui n'a pas engendré et n'a pas été engendré.",
    src: [["Texte", "Coran 112"], ["Texte", "Coran 1:1-3"]] },

  { k: ["hajj", "pelerinage", "arafat", "omra", "umra", "tawaf"], title: "Qu'est-ce que le Hajj ?",
    a: "Le Hajj est le pèlerinage à La Mecque, obligatoire une fois dans la vie pour celui qui en a la capacité. Il comprend notamment l'ihram, le tawaf, le sa'i entre Safa et Marwa, la station à Arafat (9 Dhul-Hijja), la nuit à Muzdalifa et la lapidation à Mina.",
    src: [["Texte", "Coran 3:97"], ["Texte", "Coran 2:196-203"], ["Hadith", "Hadith de Jabir (Muslim 1218)"]] },
  { k: ["isra", "miraj", "nocturne", "ascension", "aqsa"], title: "Que sont l'Isra et le Mi'raj ?",
    a: "L'Isra est le voyage nocturne du Prophète ﷺ de la Mosquée sacrée à Al-Aqsa. Le Mi'raj est son ascension à travers les cieux. La prière (cinq par jour) a été prescrite à cette occasion selon les hadiths authentiques.",
    src: [["Texte", "Coran 17:1"], ["Texte", "Coran 53:1-18"], ["Hadith", "Bukhari 349 ; Muslim 162"]], nuance: "Les détails du récit sont longs ; ils sont rapportés dans plusieurs hadiths." },
  { k: ["badr", "bataille", "uhud", "fosse", "khandaq"], title: "Quelles sont les grandes batailles de Médine ?",
    a: "Badr (an 2, Ramadan) : victoire des musulmans, moins nombreux. Uhud (an 3) : revers après que des archers ont quitté leur poste. Le Fossé (an 5) : les musulmans creusent un fossé sur le conseil de Salman al-Farisi et la coalition se retire.",
    src: [["Texte", "Coran 3:123 (Badr)"], ["Texte", "Coran 3:121-175 (Uhud)"], ["Texte", "Coran 33:9-25 (Al-Ahzab)"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["hudaybiya", "traite", "conquete"], title: "Que s'est-il passé à Hudaybiya puis à la conquête de La Mecque ?",
    a: "En l'an 6, le traité de Hudaybiya prévoit une trêve d'environ dix ans ; le Coran l'appelle une victoire éclatante. En l'an 8, après la rupture du traité par les Quraysh, La Mecque est prise presque sans combat et le Prophète ﷺ pardonne à ses anciens ennemis.",
    src: [["Texte", "Coran 48:1"], ["Hadith", "Bukhari 4844"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["bakr", "calife", "siddiq"], title: "Qui était Abu Bakr ?",
    a: "Abu Bakr as-Siddiq est l'un des premiers musulmans, le compagnon du Prophète ﷺ lors de l'Hégire et le premier calife. Sous son califat, le Coran a été rassemblé en un recueil sur l'initiative de Zayd ibn Thabit.",
    src: [["Texte", "Coran 9:40"], ["Hadith", "Bukhari 4986"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["bilal", "adhan", "muezzin"], title: "Qui était Bilal ?",
    a: "Bilal ibn Rabah, d'origine abyssine, a été affranchi par Abu Bakr après avoir été torturé pour sa foi. Il est devenu le premier muezzin de l'islam à Médine.",
    src: [["Hadith", "Bukhari 1149 ; Muslim 2458"], ["Hadith", "Abu Dawud 499 (origine de l'adhan)"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["ibrahim", "abraham", "kaaba", "zamzam", "ismael", "ismail"], title: "Qui était Ibrahim ?",
    a: "Ibrahim est appelé l'ami d'Allah. Il a combattu l'idolâtrie, a été sauvé du feu, a installé Hajar et Ismaïl à La Mecque (où jaillit Zamzam) et a construit la Kaaba avec Ismaïl.",
    src: [["Texte", "Coran 21:51-70"], ["Texte", "Coran 2:124-129"], ["Texte", "Coran 37:99-113"]] },
  { k: ["adam", "iblis", "satan"], title: "Qui était Adam ?",
    a: "Adam est le premier homme et le premier prophète. Selon le Coran, il a été créé d'argile, les anges se sont prosternés devant lui sauf Iblis, et après sa faute, Allah a accepté son repentir.",
    src: [["Texte", "Coran 2:30-39"], ["Texte", "Coran 7:11-25"]], nuance: "Le Coran dit « son épouse » ; le nom Hawwa (Ève) vient de la tradition." },
  { k: ["nouh", "noe", "deluge", "arche"], title: "Qui était Nouh (Noé) ?",
    a: "Nouh a appelé son peuple à Allah pendant de longues années. Sur l'ordre d'Allah il a construit une arche ; les croyants ont été sauvés du déluge.",
    src: [["Texte", "Coran 71"], ["Texte", "Coran 11:25-49"], ["Texte", "Coran 29:14"]] },
  { k: ["qibla", "direction", "kaaba", "jerusalem"], title: "Pourquoi prie-t-on vers la Kaaba ?",
    a: "Au début, les musulmans priaient vers Jérusalem. Environ 16 à 17 mois après l'arrivée à Médine, le Coran a ordonné de se tourner vers la Mosquée sacrée de La Mecque.",
    src: [["Texte", "Coran 2:142-150"], ["Hadith", "Bukhari 40"]] },
  { k: ["khadija"], title: "Qui était Khadija ?",
    a: "Khadija bint Khuwaylid était une commerçante de La Mecque, la première épouse du Prophète ﷺ et la première personne à croire en son message. Elle l'a réconforté après la première révélation.",
    src: [["Hadith", "Bukhari 3"], ["Histoire", "Sîra d'Ibn Hichâm"]] },
  { k: ["jumua", "vendredi", "aid", "fete", "fetes"], title: "Que sont le vendredi et les deux Aïd ?",
    a: "Le vendredi, on prie la Jumu'a à la place de Dhuhr après un sermon. L'Aïd al-Fitr marque la fin du Ramadan ; l'Aïd al-Adha a lieu le 10 Dhul-Hijja et rappelle l'épreuve d'Ibrahim.",
    src: [["Texte", "Coran 62:9-10"], ["Texte", "Coran 37:102-107"]] },
];
const normAI = s => s.toLowerCase().normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[^a-z0-9 ]/g, " ");
function askAI(query) {
  const words = normAI(query).split(/\s+/).filter(w => w.length > 2);
  let best = null, bs = 0;
  KB.forEach(e => { const s = e.k.filter(k => words.some(w => w.startsWith(k) || k.startsWith(w))).length; if (s > bs) { bs = s; best = e; } });
  return bs ? best : null;
}
